### ISSUE TITLE
Feature 1: User can search by movie title

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search by movie title.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Typing a movie title in the search bar and clicking on the `search` icon will query the API to find matches.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-02-14 at 2 00 43 PM](https://user-images.githubusercontent.com/67080126/153953778-505b8529-cf4b-4433-b5a8-bf038c6608fb.png)

![Screen Shot 2022-02-14 at 2 02 48 PM](https://user-images.githubusercontent.com/67080126/153954053-a8a369e7-205d-43eb-b485-f0c61b5258de.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add a background image.
- [x] Create a header and:
   - [x] Make the position fixed.
   - [x] Make `Movie +` link that will view the homepage.
   - [x] Make `My Watchlist` link that will view your watchlist.
- [x] Add a `div[data-view="home"]` to the HTML.
- [x] Create a search bar and:
  - [x] Make input field required.
  - [x] Style input field when focused.
  - [x] Add search icon that will query the API to find matches for the input.
- [x] Listen for `submit` events on search form and:
  - [x] Put the search form's input value into your data model (new object).
  - [x] Add the `imdbID`, `Poster`, `Title`, `Year` values for each search result to your data model.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
