### ISSUE TITLE
Feature 2: User can view search results

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view search results.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user submits their search, a list of movie cards (poster and `Details` button)are rendered if there is a match or a message stating `No results found for "${search input}"`.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-02-14 at 12 45 39 PM](https://user-images.githubusercontent.com/67080126/153943732-bcaadbbd-82ac-4b07-9747-0cdb49b65df8.png)

![Screen Shot 2022-02-14 at 12 51 02 PM](https://user-images.githubusercontent.com/67080126/153944537-dcf2bafc-e6f8-4489-8947-3f6f459844a5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling `div[data-view="search-results"]` to the HTML.
- [x] Define a function that switches views between `home` and `search-results`.
- [x] Add a search bar and:
  - [x] Make input field required.
  - [x] Style input field when focused.
  - [x] Add search icon that will query the API to find matches for the input.
- [x] Add a `p` element that will have a message based on either the error or success of the search. 
- [x] Add an unordered list to the `div[data-view="search-results"]` element with dummy search results and style them to match the wireframe.
- [x] Ensure that submitting a search appends the search results to the DOM.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
