### ISSUE TITLE
Feature 3: User can add movie to watchlist

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add movie to watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the `search-results-view`, clicking the `Details` button will render the movie information card (poster, title, year, plot, director, & cast). Clicking the `plus` icon will add a movie to your watchlist turning that icon to a `check` icon. Clicking the `check` icon will reverse the process. Clicking the `back` arrow will return you to your `search-results-view`.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-02-14 at 2 06 08 PM](https://user-images.githubusercontent.com/67080126/153954694-7956e16c-0177-4e7f-a2c0-f5e093ef4290.png)

![Screen Shot 2022-02-14 at 2 06 53 PM](https://user-images.githubusercontent.com/67080126/153954715-a747d135-42e0-4619-ad34-134599617f57.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling `div[data-view="movie-info"]` to the HTML.
- [x] Listen for `click` events on the `movie-card-info-container` that will switch views to `movie-info`.
- [x] Ensure that clicking on `movie-card-info-icon` or `movie-card-info-text` will grab the closest `data-movie-id` and save it to `data.selectedMovieId`.
- [x] Create a function that will query the API with the `data.selectedMovieId`.
- [x] Ensure the API query results are appended to the DOM.
- [x] Create a function that will add a movie to the `data.watchlist` when clicking on `.info-card-nav-add` icon.
- [x] Ensure that clicking the `info-card-nav-back` icon goes back to the previous screen.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
