### ISSUE TITLE
Feature 4: User can view watchlist

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on the `My Watchlist` link will render movie cards of movies added to your watchlist. If no movies are added there will be a message stating `WATCHLIST EMPTY`.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-02-14 at 2 11 44 PM](https://user-images.githubusercontent.com/67080126/153955181-b521b6f6-3ad8-464e-b8dc-5b2b02162f8b.png)

![Screen Shot 2022-02-14 at 2 14 34 PM](https://user-images.githubusercontent.com/67080126/153955509-e4066022-94f7-418d-94de-1ce2574472b4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling `div[data-view="watchlist"]` to the HTML.
- [x] Listen for click events on the`.watchlist` element that will switch views to `watchlist`.
- [x] Create a function that searches `data.watchlist` and appends the appropriate message and movies to the `watchlist` view.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
