### ISSUE TITLE
Feature 5: User can remove movie from watchlist

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove movie from watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the `watchlist-view`, clicking the `Details` button will render the movie information card (poster, title, year, plot, director, & cast). Clicking the `check` icon will remove a movie from your watchlist turning that icon to a `plus` icon. Clicking the `plus` icon will reverse the process. Clicking the `back` arrow will return you to your `watchlist-view`.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-02-14 at 2 39 03 PM](https://user-images.githubusercontent.com/67080126/153958543-d2781b2e-d0bb-487c-985b-8aefed215907.png)

![Screen Shot 2022-02-14 at 2 42 52 PM](https://user-images.githubusercontent.com/67080126/153959028-8e1ca569-eabb-41da-bb9d-d31449a71d73.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Ensure that clicking on `.info-card-nav-add-remove` icon will remove a movie from the `data.watchlist` and the `.watchlist-movie-cards-container`.
- [x] Ensure that clicking the `info-card-nav-back` icon goes back to the previous screen.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
